### ISSUE TITLE
Suggestions for mathematical symbols (and more)

### ISSUE THREAD

**Issue by neildawson** [reefdog/substitutions#1]
- `->` for →
- `<-` for ←
- `x*` for ×
- `//` for ÷
- `=/=` and `!=` for ≠
- `+-` for ±
- `c/o` for ℅
- `<3` for :heart: 
- `...` for …
- `(c)` for ©
- `(p)` for ℗
- `(r)` for ®

**Comment by reefdog** [comment]
These are excellent. Thank you @neildawson. Here is your green square: 🟩.

**Comment by neildawson** [comment]
I'M NOT DONE YET

- `=>` and `>=` for ≥
- `=<` and `<=` for ≤
- `/degc` for ℃
- `/degf` for ℉
- `Llan` for [Llanfair­pwllgwyngyll­gogery­chwyrn­drobwll­llan­tysilio­gogo­goch](https://en.wikipedia.org/wiki/Llanfairpwllgwyngyll)

**Comment by reefdog** [comment]
looool@`Llan`
